### ISSUE TITLE
Endless loading (infinite loop ?)

### ISSUE THREAD

**Issue by AlexIndeegoGames** [aliessmael/Unity-Contacts-List#10]
Hi there,

I'm back ! :D
I have another issue, only on Android. I am stuck on an infinite loop during the loading. Actually, I tested on 4 differente devices, it happens on 2 of them.
I tracked the bug by myself and it seems that it is in your contactsList.java LoadInformation_thread() function. I was stuck on the "while (!c.unityGotThis);" instruction, even if the "static byte[] getContact( int id )" was called, and move unityGotThis to true.
I think it happens because the variable is not atomic, so just add "volatile" when declare "static boolean unityGotThis" works and/or sleep during the loop "Thread.Sleep(1)" works too.

Cheers !

Alex

**Comment by aliessmael** [comment]
Great
