### ISSUE TITLE
custom handling access denied to contacts and a delegate function

### ISSUE THREAD

**Issue by dryaf** [aliessmael/Unity-Contacts-List#3]
hi,

when contacts are denied by the user it should be possible to react in a custom way to it.
for example this is how the v0xelbusters asset does it

1) you call LoadContacts(OnReceiveContacts)  and pass an function to it that is called when contactloading process is done (the app also doesn't block)
2) the OnReceiveContacts method should receive 2 params
- the authorization status ( ok, denied, restricted, no_choice_was_made)
- and the contactlist

This way we can handle all possible outcomes the way we want.
For example i show a loading screen when calling load.
and in the OnReceiveContacts method I close the loading screen.
and show a custom screen that explains how to unlock contacts in the settings.

**Comment by aliessmael** [comment]
so this is for IOS right?

**Comment by aliessmael** [comment]
I tried on android to make it not blocking, but it was lagging a lot, I will check and try again

**Comment by aliessmael** [comment]
Hi . I have committed new version .
You can pass 2 parameter now to loadContact
"OnDone()", "OnFai( string error)l" 
contacts will load in separate thread, and it will give you contacts one by one while thread is running to give fast an smooth loading feeling
once thread is done it will send "onDone" message
actually only android is thread right now, for ios i prepare code structure to make it thread next version
Could you check if this is fine, so i close this issue

**Comment by aliessmael** [comment]
IOS loading is asynchronous now.

**Comment by dryaf** [comment]
Hi,
I'm terribly sorry, I haven't checked back on this issue as I'm drowning in todos. 
Im looking forward to try it out, although I don't know when this will be.
As the Voxelbusters rarely release something and didn't care about the android bug for months I'll have to switch at some point.
Thank you
