### ISSUE TITLE
Contact Emails always empty

### ISSUE THREAD

**Issue by lhagan-FFX** [aliessmael/Unity-Contacts-List#4]
In IOS, when the contacts are loaded it does not seem to get email addresses because the count on the emails list for every contact is 0. I turned on the log in Contact.cs and it always said the size was 0. In Contacts.cs I logged the string that is returned as seen below. 

```
#elif UNITY_IOS
string str = getContact( index);
Debug.Log("Contact string ==" + str);
data = System.Convert.FromBase64String( str );
#endif
Contact c   = new Contact();
debug( "Data length for " + index + " is " + data.Length );
c.FromBytes( data );
Contacts.ContactsList.Add( c );
```

Once converted it returns "Ross Stiller (888) 888-8888home" but never has an email. Any help with this issue would be greatly appreciated. This was tested using an IPhone 6 on IOS 9.2.1 and an IPhone 5s on IOS 8.1.2.

**Comment by aliessmael** [comment]
Fixed
